- name: Docker install and setup
  hosts: all
  gather_facts: true
  become: true
  tasks:
  # this section from: https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-22-04
    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04" and ansible_distribution_release == "jammy"

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true
        install_recommends: true

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Check if docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Install binfmt
      community.docker.docker_container:
        name: binfmt
        image: tonistiigi/binfmt:latest
        command: --install all
        privileged: true
        state: started
        cleanup: true
        detach: false

    - name: Get buildx setting
      ansible.builtin.command: docker buildx ls
      register: buildx_output
      changed_when: false

    - name: Check if arm64 is enabled
      ansible.builtin.debug:
        msg: "arm64 is enabled"
      when: buildx_output is search("linux/arm64")

    - name: Check if arm64 is not enabled
      ansible.builtin.fail:
        msg: "arm64 is not enabled"
      when: buildx_output is not search("linux/arm64")
